### PR TITLE
Add splashscreen with disclaimer text

### LINKED ISSUE #615: Add splashscreen
Related:
https://github.com/Deltares/fews-web-oc/pull/345
https://github.com/Deltares/fews-web-oc/pull/409
https://github.com/Deltares/fews-web-oc/pull/386
https://github.com/Deltares/fews-web-oc/pull/357

### LINKED ISSUE #691: Terms of use not present in info menu
In Durban, the terms of use is configured to be present in the help menu, but it does not show up:

image

with config:

```
{
  "general" : {
    "title" : "ETheKwini Early Warning System",
    "icons" : {
      "favicon" : "ethekwini_favicon.jpg",
      "logo" : "ethekwini_logo.png"
    },
    "defaultComponent" : "topologyDisplay",
    "splashScreen" : "ethekwini_splash.png",
    "helpMenu" : {
      "url" : [ {
        "name" : "Documentation",
        "url" : "https://github.com/Deltares/fews-web-oc"
      } ],
      "path" : [ {
        "name" : "Terms of use",
        "path" : "terms-of-use"
      } ]
    },
    "readonlyMode" : true,
    "permissionsEnabled" : true
  },
  "components" : [ {
    "id" : "topologyDisplay",
    "type" : "TopologyDisplay",
    "title" : "Overview",
    "showLeafNodesAsButtons" : false,
    "defaultPath" : {
      "nodeId" : "viewer_saws_1x1"
    }
  }, {
    "id" : "htmlDisplay",
    "type" : "HtmlDisplay",
    "title" : "Terms of use",
    "path" : "terms-of-use",
    "url" : "terms-of-use.html"
  } ]
}
```

### PR DESCRIPTION
**Pull request by hvangeffen**
Closes #615, closes #691

### CODE REVIEW

**Comment by hvangeffen** [comment]
Maybe also move UAE Metoc centre text to vue, since this is what it looks like on mobile size:
image

**Review by vanmeeuwen — APPROVED** [review]

**Review by vanmeeuwen — APPROVED** [review]

**Comment by hvangeffen** [comment]
image

Text illegible with this splashscreen image.

**Comment by hvangeffen** [comment]
Handled #691 here

**Review by vanmeeuwen — APPROVED** [review]

**Comment by hvangeffen** [comment]
Also works with recently set content security policy headers

**Pull request merged**
