### PR TITLE
Move workflow button to toolbar

### LINKED ISSUE #797: Move workflow button to side menu

### LINKED ISSUE #832: Starting a succesful workflow should notify the user
https://issuetracker.deltares.nl/browse/DWO-654?focusedId=934584&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-934584

### PR DESCRIPTION
**Pull request by ceesvoesenek**
Closes #797 
Closes #832 
This is a rather involved change since the workflow control needs data from the topology and the current WMS layer (start and end times). Furthermore, I extracted some functionality from `WorkflowControl` to separate modules.

### CODE REVIEW

**Comment by hvangeffen** [comment]
## Bounding box stays active when switching to layer without workflow and or bbox workflow:
image

**Comment by hvangeffen** [comment]
## WQPS workflow is empty on first select 
http://localhost:5173/topology/node/water_level/oceanographic_water_level_d3d/map/oceanographic_water_level_d3d
image

### After reopening window
image

**Comment by hvangeffen** [comment]
## Weird spacing on bbox selection click without having drawn a bbox yet
image

**Comment by ceesvoesenek** [comment]
> ## Maybe disable button or always have a workflow selected
> 
> image

We now auto-select the first workflow, so this no longer occurs.

**Comment by ceesvoesenek** [comment]
> ## WQPS workflow is empty on first select
> 
> http://localhost:5173/topology/node/water_level/oceanographic_water_level_d3d/map/oceanographic_water_level_d3d image
> ### After reopening window
> 
> image

This is also fixed with auto-selecting the first workflow. In addition, we now show the workflow ID in the selection box if no description of the workflow is provided.

**Comment by ceesvoesenek** [comment]
> ## Weird spacing on bbox selection click without having drawn a bbox yet
> 
> image

image

We now show a dash instead of an empty string when no bounding box has been drawn yet.

**Comment by ceesvoesenek** [comment]
> ## Bounding box stays active when switching to layer without workflow and or bbox workflow:
> 
> image

We now stop the bounding box selection and abandon the work flow when switching nodes.

**Comment by hvangeffen** [comment]
## Values become NaN and menu / bbox selector break when changing delta to invalid values / below 1 (i.e. 0.3)
image

**Comment by ceesvoesenek** [comment]
> ## Workflow button disappears when scrolling
> 
> image

Now fixed, the toolbar is part of the unscrollable part of the side bar.

**Comment by hvangeffen** [comment]
## New warning
image

### SpatialDisplay.vue
```vue
      <SpatialDisplayComponent
        :layer-name="props.layerName"
        :location-id="props.locationId"
        :latitude="props.latitude"
        :longitude="props.longitude"
        :filter-ids="props.filterIds"
        @changeLocationId="onLocationChange"
        :layer-capabilities="layerCapabilities"
        :times="times"
        v-model:elevation="elevation"
        v-model:current-time="currentTime"
        @coordinate-click="onCoordinateClick"
        :secondaryWorkflows="secondaryWorkflows"
      ></SpatialDisplayComponent>
```

Have to remove :secondaryWorkflows here and maybe also in the parents

**Comment by ceesvoesenek** [comment]
Trying to draw a bounding box with x-step 0.2 and y-step 0.3 leads to errors from Terra Draw for some reason.

image

**Comment by hvangeffen** [comment]
> Trying to draw a bounding box with x-step 0.2 and y-step 0.3 leads to errors from Terra Draw for some reason.
> 
> image

Terra draw has a default max coordinate precision of 9 decimals.
Fixed in: https://github.com/Deltares/fews-web-oc/pull/839/commits/181c3767464a1e56fd407915a1f113f38cde4611

**Pull request merged**
